### ISSUE TITLE
README Mentions nonexistent scripts

### ISSUE THREAD

**Issue by dsklopp** [seizadi/secops#2]
Please reference where to get the following programs / scripts

- dropdb
- createdb
- migrate
  - Used by the Makefile target "migrate-up"

**Comment by seizadi** [comment]
dropdb and createdb are postgres tools, project built around postgres

migrate - part of go-migrate tooling https://github.com/golang-migrate/migrate
https://github.com/golang-migrate/migrate#basic-usage

I updated README...
https://github.com/seizadi/secops#prerequisites
